on:
  push:
    branches:
      - main
name: 🚀 Deploy waterbilling system on push
jobs:
  web-deploy:
    name: 🎉 Deploy water billing Server
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: waterbilling.uk.tempcloudsite.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /
        exclude: |
          **/application/cache/**
          **/application/config/config.php
          **/application/config/database.php
          **/application/config/constant.php
          **/.buildpath/**
          .ftp-deploy-sync-state.json
          .git-ftp.log
          .project
          .htaccess
          error_log